export default function EvidenceBadge({ type, source, verificationStatus }) {
  const normalized = (type || 'AI_INFERENCE').toUpperCase();

  const configs = {
    DATA: {
      label: 'DATA',
      bgColor: 'rgba(16, 185, 129, 0.15)',
      borderColor: '#10B981',
      textColor: '#10B981',
      icon: '✓',
      tooltip: 'Verified external empirical data from live search provider',
    },
    AI_INFERENCE: {
      label: 'AI INFERENCE',
      bgColor: 'rgba(56, 189, 248, 0.15)',
      borderColor: '#38BDF8',
      textColor: '#38BDF8',
      icon: '⚡',
      tooltip: 'Synthesized by Ollama llama3.2:3b parametric reasoning',
    },
    ASSUMPTION: {
      label: 'ASSUMPTION',
      bgColor: 'rgba(245, 158, 11, 0.15)',
      borderColor: '#F59E0B',
      textColor: '#F59E0B',
      icon: '⚠️',
      tooltip: 'Unvalidated hypothesis requiring target customer validation',
    },
    RECOMMENDATION: {
      label: 'RECOMMENDATION',
      bgColor: 'rgba(139, 92, 246, 0.15)',
      borderColor: '#8B5CF6',
      textColor: '#C084FC',
      icon: '💡',
      tooltip: 'Strategic guidance generated by specialized agent workflow',
    },
  };

  const cfg = configs[normalized] || configs.AI_INFERENCE;

  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.35rem',
        padding: '0.2rem 0.55rem',
        borderRadius: '6px',
        fontSize: '0.68rem',
        fontFamily: 'var(--font-mono)',
        fontWeight: '700',
        letterSpacing: '0.04em',
        background: cfg.bgColor,
        border: `1px solid ${cfg.borderColor}`,
        color: cfg.textColor,
        whiteSpace: 'nowrap',
        boxShadow: `0 0 10px ${cfg.borderColor}22`,
      }}
      title={cfg.tooltip}
    >
      <span>{cfg.icon}</span>
      <span>[{cfg.label}]</span>
      {source && (
        <span style={{ color: 'var(--text-muted)', fontWeight: '400', fontSize: '0.62rem' }}>
          • {source}
        </span>
      )}
    </span>
  );
}
